string=input("enter the string\n")
str1=input("enter the string which should be replace\n")
str2=input("enter the string ,st1 should be replace with\n")
string=string.replace(str1,str2)
print("string after replacement")
print(string)